export type MemberType = "member" | "mentor";

export interface MemberProfile {
  id: string;
  name: string;
  roleId: string;
  roleEn: string;
  type: MemberType;
  imagePlaceholder: string;
  majorId?: string;
  majorEn?: string;
  universityId?: string;
  universityEn?: string;
  achievementsId?: string[];
  achievementsEn?: string[];
}

export const members: MemberProfile[] = [
  {
    id: "t-01",
    name: "Rizkiyah Ananda",
    roleId: "President",
    roleEn: "President",
    type: "member",
    imagePlaceholder: "/images/members/Rizkiyah Ananda President.jpeg",
  },
  {
    id: "t-02",
    name: "Andi Putri",
    roleId: "Head of Media",
    roleEn: "Head of Media",
    type: "member",
    imagePlaceholder: "/images/members/Andi Putri_Head of Media.JPG",
  },
  {
    id: "t-03",
    name: "Andi Shifa Salsabillah",
    roleId: "Head Of HRD",
    roleEn: "Head Of HRD",
    type: "member",
    imagePlaceholder: "/images/members/Andi Shifa Salsabillah_Head Of HRD.JPG",
  },
  {
    id: "t-04",
    name: "Fathinah N Jannah",
    roleId: "Head Of R&E",
    roleEn: "Head Of R&E",
    type: "member",
    imagePlaceholder: "/images/members/Fathinah N Jannah_Head Of R&E.JPG",
  },
  {
    id: "m-01",
    name: "Annisa A Maharani",
    roleId: "Sekretaris",
    roleEn: "Secretary",
    type: "member",
    imagePlaceholder: "/images/members/Annisa A Maharani_Secretary.JPG",
  },
  {
    id: "m-02",
    name: "Nur Qalby Salsabila",
    roleId: "Bendahara",
    roleEn: "Treasurer",
    type: "member",
    imagePlaceholder: "/images/members/Nur Qalby Salsabila_Bendahara.JPG",
  },
  {
    id: "m-03",
    name: "Angel E.Th Manuputty",
    roleId: "Staff HRD",
    roleEn: "Staff HRD",
    type: "member",
    imagePlaceholder: "/images/members/Angel E.Th Manuputty_Staff HRD.JPG",
  },
  {
    id: "m-04",
    name: "Safrina Inayah",
    roleId: "Staff HRD",
    roleEn: "Staff HRD",
    type: "member",
    imagePlaceholder: "/images/members/Safrina Inayah_Staff HRD.JPG",
  },
  {
    id: "m-05",
    name: "Aulia Khairunnisa Isman",
    roleId: "Staff Media",
    roleEn: "Staff Media",
    type: "member",
    imagePlaceholder: "/images/members/Aulia K Isman_Staff Media.JPG",
  },
  {
    id: "m-06",
    name: "Najwa P Larasati",
    roleId: "Staff Media",
    roleEn: "Staff Media",
    type: "member",
    imagePlaceholder: "/images/members/Najwa P Larasati_Staff Media.JPG",
  },
  {
    id: "m-07",
    name: "Nasywa E Apsari",
    roleId: "Staff Media",
    roleEn: "Staff Media",
    type: "member",
    imagePlaceholder: "/images/members/Nasywa E Apsari_Staff Media.JPG",
  },
  {
    id: "m-08",
    name: "Nur F S Jaga",
    roleId: "Staff Media",
    roleEn: "Staff Media",
    type: "member",
    imagePlaceholder: "/images/members/Nur F S Jaga_Staff Media.JPG",
  },
  {
    id: "m-09",
    name: "Dhiska D Hermalia H",
    roleId: "Staff Program",
    roleEn: "Staff Program",
    type: "member",
    imagePlaceholder: "/images/members/Dhiska D Hermalia H_Staff Program.JPG",
  },
  {
    id: "m-10",
    name: "Mevie Heatubun",
    roleId: "Staff Program",
    roleEn: "Staff Program",
    type: "member",
    imagePlaceholder: "/images/members/Mevie Heatubun_Staff program.jpg",
  },
  {
    id: "m-11",
    name: "Putri Atiqah Rana",
    roleId: "Staff Program",
    roleEn: "Staff Program",
    type: "member",
    imagePlaceholder: "/images/members/Putri Atiqah Rana_Staff Program.jpeg",
  },
  {
    id: "m-12",
    name: "Shafiyyah N F Salandra",
    roleId: "Staff Program",
    roleEn: "Staff Program",
    type: "member",
    imagePlaceholder: "/images/members/Shafiyyah N F Salandra_Staff Program.JPG",
  },
  {
    id: "m-13",
    name: "Nurul Marasabessy",
    roleId: "Staff R&E",
    roleEn: "Staff R&E",
    type: "member",
    imagePlaceholder: "/images/members/Nurul Marasabessy_Staff RE.JPG",
  },
  {
    id: "m-14",
    name: "Sabina J. Tutupoho",
    roleId: "Staff R&E",
    roleEn: "Staff R&E",
    type: "member",
    imagePlaceholder: "/images/members/Sabina J. Tutupoho_Staff R&E.JPG",
  },
  {
    id: "m-15",
    name: "Dinah Zhafirah",
    roleId: "Staff HRD",
    roleEn: "Staff HRD",
    type: "member",
    imagePlaceholder: "/images/members/Dinah Zhafirah_Staff HRD.JPG",
  },
  {
    id: "m-16",
    name: "Vashajadyah A F Ahmad",
    roleId: "Head Of Program",
    roleEn: "Head Of Program",
    type: "member",
    imagePlaceholder: "/images/members/Vashajadyah A F Ahmad_Head Of Program.JPG",
  },
  {
    id: "m-17",
    name: "Ikha Hilwa R. Khaliky",
    roleId: "Staff Media",
    roleEn: "Staff Media",
    type: "member",
    imagePlaceholder: "/images/members/IKHA Hilwa R. Khaliky_ Staff Media.JPG",
  },
  {
    id: "mentor-01",
    name: "Arifah Deswina",
    roleId: "Mentor",
    roleEn: "Mentor",
    type: "mentor",
    imagePlaceholder: "/images/mentors/Arifah Deswina_Mentor.png",
    majorId: "Teknik Informatika",
    majorEn: "Informatics Engineering",
    universityId: "Universitas Hasanuddin",
    universityEn: "Hasanuddin University",
    achievementsId: [
      "Awardee Young Leaders for Indonesia (YLI) Wave 17 by Mckinsey & Co.",
      "Awardee beasiswa riset Badan Amil Zakat Nasional (BAZNAS) 2025-2026",
      "The Generation IMPACT Student Ambassador by Schneider Electric 2024-2025",
    ],
    achievementsEn: [
      "Awardee Young Leaders for Indonesia (YLI) Wave 17 by Mckinsey & Co.",
      "Awardee of the BAZNAS research scholarship 2025-2026",
      "The Generation IMPACT Student Ambassador by Schneider Electric 2024-2025",
    ],
  },
  {
    id: "mentor-02",
    name: "Zikra Nagasuri",
    roleId: "Mentor",
    roleEn: "Mentor",
    type: "mentor",
    imagePlaceholder: "/images/mentors/Zikra Nagasuri_Mentor.png",
    majorId: "Teknik Lingkungan",
    majorEn: "Environmental Engineering",
    universityId: "Universitas Hasanuddin",
    universityEn: "Hasanuddin University",
    achievementsId: [
      "Participant of Pre-ETIC Program – Kanazawa University, Japan & Awardee of JASSO Scholarship (2025/2026)", 
      "1st Place Winner – Scientific Writing Competition HLHS, PT IMIP (2025)",
      "Funded Research Awardee – PKM-RE (Program Kreativitas Mahasiswa – Riset Eksakta) (2024)",
    ],
    achievementsEn: [
      "Participant of Pre-ETIC Program – Kanazawa University, Japan & Awardee of JASSO Scholarship (2025/2026)", 
      "1st Place Winner – Scientific Writing Competition HLHS, PT IMIP (2025)",
      "Funded Research Awardee – PKM-RE (Program Kreativitas Mahasiswa – Riset Eksakta) (2024)",
    ],
  },
  {
    id: "mentor-03",
    name: "Khadija Karepesina",
    roleId: "Mentor",
    roleEn: "Mentor",
    type: "mentor",
    imagePlaceholder: "/images/mentors/Arifah Deswina_Mentor.png",
    majorId: "Dummy Major",
    majorEn: "Dummy Major",
    universityId: "Universitas Pattimura",
    universityEn: "Pattimura University",
    achievementsId: [
      "Google Ambassador", 
      "Mapres Unpattimurra",
      "PMM Batch 4",
    ],
    achievementsEn:  [
      "Google Ambassador", 
      "Mapres Unpattimurra",
      "PMM Batch 4",
    ],
  },
  {
    id: "mentor-04",
    name: "Renny Rosa",
    roleId: "Mentor",
    roleEn: "Mentor",
    type: "mentor",
    imagePlaceholder: "/images/mentors/Renny Rosa_Mentor.png",
    majorId: "Hubungan Internasional",
    majorEn: "International Relations",
    universityId: "Universitas Kristen Indonesia",
    universityEn: "Universitas Kristen Indonesia",
    achievementsId: [
      "Regional Women's Committee WSCF AP (2025-2027)",
      "Pembicara dalam Seminar 'Jaga Perempuan Indonesia' sub tema : “Merekam Jejak Perempuan Merebut Ruang dan Partisipasi Publik di Indonesia: Dari Kolonialisme hingga Era Digital” oleh DPP BMI Tahun 2026",
      "Pelatihan Fasilitator Perempuan dengan Tema 'Ruang Aman untuk Perempuan' DPP GAMKI Tahun 2025",
    ],
    achievementsEn: [
      "Regional Women's Committee, WSCF AP (2025–2027)",
      "Speaker at the 'Protect Indonesian Women' (Jaga Perempuan Indonesia) Seminar; Sub-theme: “Tracing Women’s Footsteps in Reclaiming Space and Public Participation in Indonesia: From Colonialism to the Digital Era,” organized by the BMI Central Board (2026)",
      "Women’s Facilitator Training; Theme: “Safe Spaces for Women,” organized by the GAMKI Central Board (2025)",
    ],
  },
  {
    id: "mentor-05",
    name: "Mentor Dummy 04",
    roleId: "Mentor",
    roleEn: "Mentor",
    type: "mentor",
    imagePlaceholder: "/images/mentors/Arifah Deswina_Mentor.png",
    majorId: "Dummy Major",
    majorEn: "Dummy Major",
    universityId: "Dummy University",
    universityEn: "Dummy University",
    achievementsId: ["Dummy achievement 1", "Dummy achievement 2"],
    achievementsEn: ["Dummy achievement 1", "Dummy achievement 2"],
  },
];
